### ISSUE TITLE
Tor can't connect

### ISSUE THREAD

**Issue by yhardbe** [colmanmcguan/tor-capture#2]
Excuse me, I followed your prompts step by step, but it seems that I still cannot connect to the tor network. Could you please provide me with an answer? Thank you!
![image](https://github.com/csmcguan/tor-capture/assets/45647203/abcf0a7d-f9c8-47b0-a7b7-51d9c0f99ffc)
![image](https://github.com/csmcguan/tor-capture/assets/45647203/0f1b7a39-a807-48aa-9f1c-233c0a1dbc01)

**Comment by csmcguan** [comment]
This is a built-in function of the capture script to make sure Tor is up and running before visiting the website and logging the trace--if a connection is not able to be made before the timeout value, the controller shuts down Tor and restarts the capture process for the current trace. This functionality is provided in ./visit/verify_connection.py with a default timeout value of 15 seconds.

If you are on wifi, I recommend moving to a wired connection because Tor is already very slow. Alternatively, you can try increasing the timeout value.

Hope this helps.

**Comment by yhardbe** [comment]
In my country, the tor network has been censored and I have extended the capture time, but it still cannot be done.

**Comment by csmcguan** [comment]
Unfortunately, this experiment will not work if Tor is blocked in your country.
